### ISSUE TITLE
runtime: export functions to start and stop the server in Deno code

### ISSUE THREAD

**Issue by satyarohith** [denoland/deployctl#56]
Writing automated tests will be easier when we can start and stop the deploy server in Deno code.

Example code:
```js
import {
  startServer,
  stopServer,
} from "https://deno.land/x/deployctl/runtime.js";

Deno.test("body is hello world", async () => {
  startServer(8910);

  addEventListener("fetch", (event) => {
    event.respondWith(new Response("Hello world"));
  });

  const response = await fetch("http://localhost:8910");
  const body = await response.text();
  assertEquals(body, "Hello world");
  stopServer();
});
```

I'm not sure if this would be the best approach to test deploy code. Let me know your thoughts.

(cc @lucacasonato)

**Comment by kt3k** [comment]
probably blocked by https://github.com/denoland/deno/issues/10508

**Comment by lucacasonato** [comment]
Thanks for contributing by opening an issue.

This project is being archived because you can now use `deno run` to run your Deploy scripts locally: https://deno.com/deploy/docs/running-scripts-locally/. As such, I will close this issue.

If you have feedback about Deno Deploy, please open an issue on this repo: https://github.com/denoland/deploy_feedback
