### ISSUE TITLE
command error

### ISSUE THREAD

**Issue by JaneSu** [denoland/deployctl#62]
I have run install command, but there is an error:

![image](https://user-images.githubusercontent.com/20908447/123405923-ed8e9d00-d5dc-11eb-8899-86dd90228de8.png)

I haven't found any answer through Google for that error

**Comment by lucacasonato** [comment]
What version of Deno are you using? (run `deno --version`). If it is not 1.11.2, please run `deno upgrade` and confirm that the version is now 1.11.2.

**Comment by lucacasonato** [comment]
Thanks for contributing by opening an issue.

This project is being archived because you can now use `deno run` to run your Deploy scripts locally: https://deno.com/deploy/docs/running-scripts-locally/. As such, I will close this issue.

If you have feedback about Deno Deploy, please open an issue on this repo: https://github.com/denoland/deploy_feedback
