### ISSUE TITLE
Deno.test Not Recognized

### ISSUE THREAD

**Issue by quenio** [denoland/deployctl#92]
Given a module internally calls Deno.test
When `deployctl` runs a JSX that imports that module
Then the following error is shown:
```
error: TS2339 [ERROR]: Property 'test' does not exist on type 'typeof Deno'.
      return Deno.test(testName, () => assert(assertion.evaluate()));
```

**Comment by lucacasonato** [comment]
Thanks for contributing by opening an issue.

This project is being archived because you can now use `deno run` to run your Deploy scripts locally: https://deno.com/deploy/docs/running-scripts-locally/. As such, I will close this issue.

If you have feedback about Deno Deploy, please open an issue on this repo: https://github.com/denoland/deploy_feedback
